"""add thumbnail_url and status to photos

Revision ID: 7187bea0e39b
Revises: 959f0d7fbd82
Create Date: 2026-07-18 12:54:11.959159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7187bea0e39b'
down_revision = '959f0d7fbd82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('thumbnail_url')

    # ### end Alembic commands ###
