"""sync_quest_and_event_model_changes

Revision ID: b1941a458d7f
Revises: 313b3ada1976
Create Date: 2026-07-17 13:29:33.660916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1941a458d7f'
down_revision = '313b3ada1976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expired_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('need_redeem', sa.Boolean(), nullable=True))

    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_column('example_photo_path')
        batch_op.drop_column('description')
        batch_op.drop_column('requires_redeem')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('difficulty', postgresql.ENUM('easy', 'medium', 'hard', name='difficulty_enum'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('requires_redeem', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('example_photo_path', sa.VARCHAR(length=300), autoincrement=False, nullable=True))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('need_redeem')
        batch_op.drop_column('expired_date')

    # ### end Alembic commands ###
